apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-test-secret
spec:
  backendType: vault
  data:
    - name: user
      key: secrets/data/khcheck-external-secrets
      property: user
    - name: pass
      key: secrets/data/khcheck-external-secrets
      property: password
