apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "khcheck-external-secrets.fullname" . }}-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "khcheck-external-secrets.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "khcheck-external-secrets.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
